### ISSUE TITLE
Initial Decoders

### ISSUE THREAD

**Issue by penland365** [finagle/roc#51]
Decoders for Standard Value types such as 
- [x] Option
- [x] String
- [x] Short
- [x] Int
- [x] Long
- [x] Float
- [x] Double
- [x] Defined JSON type
- [x] java.time.LocalTime
- [x] java.time.LocalDate
- [x] java.time.ZonedDateTime
- [x] Boolean
- [x] Char

See [java.sql.Types](http://docs.oracle.com/javase/8/docs/api/java/sql/Types.html) for base Java information and [Postgresql Types](http://www.postgresql.org/docs/current/static/datatype.html) for information about Postgresql Types.

**Comment by penland365** [comment]
Numeric Decoders were added by #53

**Comment by penland365** [comment]
Boolean decoders added by #54

**Comment by penland365** [comment]
Char decoders added by #55

**Comment by penland365** [comment]
JSON handled by #56

**Comment by penland365** [comment]
This has been completed by #58
